# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/danihernandez/Downloads/unreal-full-extract/Linux_Unreal_Engine_5.6.1

TARGETS = \
	MuxieLLM-Android-DebugGame  \
	MuxieLLM-Android-Development  \
	MuxieLLM-Android-Shipping  \
	MuxieLLM-Linux-DebugGame  \
	MuxieLLM-Linux-Development  \
	MuxieLLM-Linux-Shipping  \
	MuxieLLM-LinuxArm64-DebugGame  \
	MuxieLLM-LinuxArm64-Development  \
	MuxieLLM-LinuxArm64-Shipping  \
	MuxieLLM \
	MuxieLLMEditor-Linux-DebugGame  \
	MuxieLLMEditor-Linux-Development  \
	MuxieLLMEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MuxieLLMEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MuxieLLMEditor-Linux-Debug


MuxieLLM-Android-DebugGame:
	 $(BUILD) MuxieLLM Android DebugGame  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-Android-Development:
	 $(BUILD) MuxieLLM Android Development  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-Android-Shipping:
	 $(BUILD) MuxieLLM Android Shipping  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-Linux-DebugGame:
	 $(BUILD) MuxieLLM Linux DebugGame  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-Linux-Development:
	 $(BUILD) MuxieLLM Linux Development  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-Linux-Shipping:
	 $(BUILD) MuxieLLM Linux Shipping  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-LinuxArm64-DebugGame:
	 $(BUILD) MuxieLLM LinuxArm64 DebugGame  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-LinuxArm64-Development:
	 $(BUILD) MuxieLLM LinuxArm64 Development  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM-LinuxArm64-Shipping:
	 $(BUILD) MuxieLLM LinuxArm64 Shipping  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLM: MuxieLLM-Linux-Development

MuxieLLMEditor-Linux-DebugGame:
	 $(BUILD) MuxieLLMEditor Linux DebugGame  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLMEditor-Linux-Development:
	 $(BUILD) MuxieLLMEditor Linux Development  -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" $(ARGS)

MuxieLLMEditor: MuxieLLMEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/danihernandez/Documents/MuxieLLM/MuxieLLM.uproject" -Game 

.PHONY: $(TARGETS)
